spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/kwonka
    username: kwonka
    password: kwonka
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

telegram:
  bot:
    username: CustomerKwonkaBot
    token: ${TELEGRAM_CUSTOMER_TOKEN:token}
  customer:
    bot:
      token: ${TELEGRAM_BARISTA_TOKEN:token}

logging:
  level:
    com.kwonka: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
    org.flywaydb: INFO