spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kwonka
    username: kwonka
    password: kwonka
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
telegram:
  bot:
    username: CustomerKwonkaBot
    token: token

logging:
  level:
    com.kwonka: INFO
    org.springframework: INFO
    org.hibernate: WARN