spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kwonka
    username: kwonka
    password: kwonka
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8082

telegram:
  bot:
    admin:
      username: AdminKwonkaBot
      token: ${TELEGRAM_ADMIN_TOKEN:token}
    barista:
      token: ${TELEGRAM_BARISTA_TOKEN:token}

logging:
  level:
    com.kwonka: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.flywaydb: INFO